### PR TITLE
Additionally support oidc-token-verifier:^1.0

### PR DESCRIPTION
**Pull request by craig410**

### CODE REVIEW

**Comment by craig410** [comment]
@acoulton having to guess at this a bit, but the [failure](https://github.com/ingenerator/cloud-tasks-wrapper/actions/runs/6660029991/job/18100551702?pr=17#step:7:29) due to the `alg` [here](https://ingenerator.github.io/oidc-auth-sandbox/openid-jwks-certs.json ) being `RSA256` where [here](https://github.com/ingenerator/cloud-tasks-wrapper/blob/0.5.x/test/integration/ServerTest.php#L111) it's keyed as `RS256`??

If I change that to `RSA256` it throws `DomainException : Algorithm not supported` so presumably we need to publish a new (or replacement) key at `oidc-auth-sandbox`?

**Comment by acoulton** [comment]
Hmm, I'm just having a quick look. `RS256` is the algorithm name as defined in JWT, it's possible that previously something in the key parsing was coping with the openid file saying `RSA...` and mapping that to the value JWT expects.

**Comment by acoulton** [comment]
Argh, ok so it's a historical typo in our test stuff. Google's [certs endpoint](https://www.googleapis.com/oauth2/v3/certs) has `"alg": "RS256"` and that matches the JWK spec, which points to the [RFC for the algorithms for use with all the JWT / JWK / etc protocols](https://www.rfc-editor.org/rfc/rfc7518.html#section-3.1)

But prior to firebase/php-jwk@v6 it didn't matter because the `alg` in the provider's JSON keys file was being ignored, we were just forcing `RS256` when comparing to the actual JWT that had been issued.

So yeah, as you say we'll need to change https://github.com/ingenerator/oidc-auth-sandbox/blob/main/openid-jwks-certs.json#L8 to `RS256` (which should be safe to do in-place because older versions of this lib ignore that anyway).

We'll also need to change the cloud-tasks-emulator, I based that cert endpoint on the tests for this package so it's wrong too https://github.com/acoulton/cloud-tasks-emulator/blob/master/oidc.go#L140 - I can look at that.

**Comment by acoulton** [comment]
OK, fixed in our fork of the emulator with https://github.com/acoulton/cloud-tasks-emulator/commit/3c478a26e5c2c15b47a8932166724da7078ea4c1 and I've released that as [ghcr.io/acoulton/cloud-tasks-emulator:1.2.5-acoulton](https://github.com/acoulton/cloud-tasks-emulator/pkgs/container/cloud-tasks-emulator/141588147?tag=1.2.5-acoulton) but need to chat to you tomorrow about tagging strategy for that fork.

**Pull request merged**
